function data = import_mark10(filename, area, min_stress)
%IMPORTFILE Import data from a text file
%  ALT304905N202259RUN1LEFT = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the numeric data.
%
%  ALT304905N202259RUN1LEFT = IMPORTFILE(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  ALT304905N202259Run1Left = importfile("C:\dyl_folders\Arieca_dyl\Projects\ROHM authoritative on Google Drive\ROHM 05102022\ALT_304_90_5N_2022_5_9_Run_1_Left.csv", [7, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 10-May-2022 14:58:21

%% Input handling

% Hardcoded Data lines
dataLines = [7, Inf];

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Reading", "Load", "Travel", "Time"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
data = readtable(filename, opts);

%% Convert to output type
data = table2array(data); % Reading (Unitless) Load (N) Travel (mm) Time (s)
data = [data, data(:, 2)/area/1000]; % Add column with shear stress (kPa)
data = above_value(data, 5, min_stress, [1:5]); % Truncate data that is lower than threshold
data = abs(data);
% data = 
end